on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    environment: release
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Verify commit exists in origin/master
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch --remote --contains | grep origin/master

      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

      - name: Build
        run: >
          dotnet build --configuration Release
          src/Musement.Extensions.Logging/Musement.Extensions.Logging.csproj
          -p:Version=${VERSION}

      - name: Test
        run: dotnet test

      - name: Pack
        run: >
          dotnet pack --configuration Release
          src/Musement.Extensions.Logging/Musement.Extensions.Logging.csproj
          -p:Version=${VERSION}
          --output .

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: Musement.Extensions.Logging.*.nupkg

      - name: Push
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: >
          dotnet nuget push ./Musement.Extensions.Logging.${VERSION}.nupkg
          -k ${NUGET_API_KEY}
          -s https://api.nuget.org/v3/index.json
